
# The bot token
TOKEN: token


# The proxy server
PROXY:
  url: http://host:port


# Message templates
MESSAGES:
  start: |
    Hi, %s! I'm a Family Assistant.
    I can help you get some information.

    You can control me by sending these commands:

    /weather - get weather

  unknown: |
    Sorry, I didn't understand that command.