
# The bot token
TOKEN: token


# The proxy server
PROXY:
  url: http://host:port


# Message templates
MESSAGES:
  start: |
    Привет, %s!
    Я - ваш семейный помощник.

    Ты можешь управлять мной с помощью этих команд:

    /weather - узнать погоду

  unknown: |
    Извини, я не знаю эту команду.

  weather: |
    Погода в Иркутске:

    Сейчас:  %s (%s)
    Сегодня: %s...%s
    Завтра:  %s...%s