
# The bot token.txt
TOKEN: 123456789:AAHh3op8TJcpCBV2w0GblN63ncOqHVpSPE0


# The proxy server
PROXY:
  url: http://host:port


# Message templates
MESSAGES:
  start: |
    Ты можешь управлять мной с помощью этих команд:

    /weather - узнать погоду

    *Погода*
    /setweatherlocation - установить географический объект
    /setweathertime - установить время для ежедневного информирования

  unknown: |
    Извини, я не знаю эту команду.

  weather: |
    Погода в Иркутске:

    Сейчас:  %s (%s)
    Сегодня: %s...%s
    Завтра:  %s...%s