
# The bot token
TOKEN: token


# The proxy server
PROXY:
  url: http://host:port


# Message templates
MESSAGES:
  EN:
    start: |
      Hi, %s!
      I am your family assistant.

      I can help you get some information.

      You can control me by sending these commands:

      /weather - get weather

    unknown: |
      Sorry, I didn't understand that command.

  RU:
    start: |
      Привет, %s!
      Я - ваш семейный помощник.

      Ты можешь управлять мной с помощью этих команд:

      /weather - узнать погоду

    unknown: |
      Извини, я не знаю эту команду.

    weather: |
      Погода в Иркутске:

      Сейчас:  %s
      Сегодня: %s...%s