
# The bot token
TOKEN: 835111842:AAHh3op8TJcpCBV2w0GblN63ncOqHVpSPE0


# The proxy server
PROXY:
  url: http://206.81.23.233:8899


# Message templates
MESSAGES:
  start: |
    Hi %s!
    You can control me by sending these commands:

    /about - about me
    /weather - get weather

  unknown: |
    Invalid command. Try again.